### ISSUE TITLE
WS2811

### ISSUE THREAD

**Issue by blackzafiqz** [judios/WS2812B-Driver-For-Azure-Sphere#1]
Can you add function for WS2811 led strip?

**Comment by judios** [comment]
It is possible. I was looking at the ws2811 specs. One can use 100000 to represent a 0 and 111000 to represent a 1. Using a bandwidth of 400ns for each bit. 
I do not have a ws2811 to test it. I can write the functions. Can you test them?

**Comment by judios** [comment]
> Can you add function for WS2811 led strip?

It is possible. I was looking at the ws2811 specs. One can use 100000 to represent a 0 and 111000 to represent a 1. Using a bandwidth of 400ns for each bit.
I do not have a ws2811 to test it. I can write the functions. Can you test them?

**Comment by judios** [comment]
Another thing to keep in mind is that the red bits go before the green bits.

**Comment by blackzafiqz** [comment]
ya sure bro, i will test it

**Comment by blackzafiqz** [comment]
why we can't write code just like this?
```
for(int i=1;i<=24;i++)
{
    gpioSet(gpiofd,high);
    nanosleep(1.2ms);
    gpioSet(gpiofd,low);
    nanosleep(1.3ms);
}
```
it still send 0xffffff right?

**Comment by judios** [comment]
1. nanosleep is not that accurate for Nanos in the azure sphere.  To the sleep time you have to add cycles consumed while calling and setting the nanosleep function. I did a test at it give me around 65 microseconds.
2. there is also the time consumed setting the gpio.

if you check the time before the loop and after the loop, you will find the difference is way more than 60 microseconds.

**Comment by judios** [comment]
I have added the driver already.
Let me know if you have any issues with it.
If you don't get proper colors, try increasing or reducing the speed  in line 83

int result = SPIMaster_SetBusSpeed(spiFd, 2400000);  // 2400000 bps
